'# ANP SDK 统一配置文件': null
'# 项目根目录自动检测，支持 {APP_ROOT} 占位符': null

multi_agent_mode:
  agents_cfg_path: '{APP_ROOT}/data_user/localhost_9527/agents_config'


log_settings:
  log_level: INFO
  detail:
    file: "{APP_ROOT}/data_tmp_log/app.log"
    max_size: 100

anp_sdk:
  debug_mode: true
  host: localhost
  port: 9527
  user_did_port_1: 9527
  user_did_port_2: 9528
  user_did_path: '{APP_ROOT}/data_user/localhost_9527/anp_users'
  user_hosted_path: '{APP_ROOT}/data_user/localhost_9527/anp_users_hosted'
  auth_virtual_dir: wba/auth
  msg_virtual_dir: /agent/message
  token_expire_time: 3600
  user_did_key_id: key-1
  group_msg_path: '{APP_ROOT}/anp_open_sdk'
  jwt_algorithm: RS256
  publisher_config_path:
  nonce_expire_minutes: 6
  helper_lang: zh
  agent:
    demo_agent1: 本田
    demo_agent2: 雅马哈
    demo_agent3: 铃木
llm:
  api_url: https://api.302ai.cn/v1
  default_model: deepseek/deepseek-chat-v3-0324:free
  max_tokens: 512
  system_prompt: 你是一个智能助手，请根据用户的提问进行专业、简洁的回复。
mail:
  use_local_backend: true
  local_backend_path: '{APP_ROOT}/data_demo_simulate/mail_local_backend'
  smtp_server: smtp.gmail.com
  smtp_port: 587
  imap_server: imap.gmail.com
  imap_port: 993
  sender_mail_user: sender@gmail.com
  register_mail_user: register@gmail.com
  hoster_mail_user: hoster@gmail.com


anp_user_service:
  user_did_path: '{APP_ROOT}/anp_user_service/anp_users'
  model_name: gpt-4.1-nano
  temperature: 0.3
  api_base: https://api.302ai.cn/v1
env_mapping:
  '# 应用配置': null
  debug_mode: ANP_DEBUG
  host: ANP_HOST
  port: ANP_PORT
  '# 系统环境变量': null
  system_path: PATH
  home_dir: HOME
  user_name: USER
  python_path: PYTHONPATH
  '# API 密钥': null
  openai_api_key: OPENAI_API_KEY
  anthropic_api_key: ANTHROPIC_API_KEY
  '# 邮件配置': null
  mail_password: MAIL_PASSWORD
  hoster_mail_password: HOSTER_MAIL_PASSWORD
  sender_mail_password: SENDER_MAIL_PASSWORD
  '# 数据库和服务': null
  database_url: DATABASE_URL
  redis_url: REDIS_URL
secrets:
- openai_api_key
- anthropic_api_key
- mail_password
- hoster_mail_password
- sender_mail_password
- database_url
env_types:
  debug_mode: boolean
  port: integer
  smtp_port: integer
  imap_port: integer
  system_path: path_list
  python_path: path_list
  home_dir: path
  token_expire_time: integer
  nonce_expire_minutes: integer
path_config:
  path_separator: ':'
  resolve_paths: true
  validate_existence: false
