# ANP SDK 统一配置文件模板
# 复制此文件为 unified_config.yaml 并根据需要修改配置

# ==========================================
# 应用核心配置
# ==========================================

log_settings:
  log_level: DEBUG
  detail:
    file: "/tmp/app.log"
    max_size: 100

anp_sdk:
  debug_mode: true                    # 调试模式
  host: localhost                     # 服务主机
  port: 9527                         # 服务端口
  
  # 路径配置（{APP_ROOT} 会自动替换为项目根目录）
  user_did_path: "{APP_ROOT}/anp_open_sdk/anp_users"
  user_hosted_path: "{APP_ROOT}/anp_open_sdk/anp_users_hosted"
  group_msg_path: "{APP_ROOT}/anp_open_sdk"

  # 虚拟目录配置
  auth_virtual_dir: "wba/auth"
  msg_virtual_dir: "/agent/message"
  
  # 安全配置
  token_expire_time: 3600             # Token过期时间（秒）
  nonce_expire_minutes: 6             # Nonce过期时间（分钟）
  jwt_algorithm: "RS256"              # JWT算法
  user_did_key_id: "key-1"           # DID密钥ID
  helper_lang: "zh"                  # 帮助语言

# ==========================================
# LLM 配置
# ==========================================
llm:
  api_url: "https://api.302ai.cn/v1"
  default_model: "deepseek/deepseek-chat-v3-0324:free"
  max_tokens: 512
  system_prompt: "你是一个智能助手，请根据用户的提问进行专业、简洁的回复。"

# ==========================================
# 邮件配置
# ==========================================
mail:
  use_local_backend: true
  local_backend_path: "{APP_ROOT}/anp_open_sdk/testuse/mail_local_backend"
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  imap_server: "imap.gmail.com"
  imap_port: 993

# ==========================================
# 环境变量映射（将环境变量映射到配置属性）
# ==========================================
env_mapping:
  # 应用配置
  debug_mode: ANP_DEBUG
  host: ANP_HOST
  port: ANP_PORT
  
  # 系统环境变量
  system_path: PATH
  home_dir: HOME
  user_name: USER
  python_path: PYTHONPATH
  
  # API 密钥（敏感信息）
  openai_api_key: OPENAI_API_KEY
  
  # 邮件密码（敏感信息）
  mail_password: MAIL_PASSWORD
  
  # 数据库连接（敏感信息）
  database_url: DATABASE_URL

# ==========================================
# 敏感信息列表（不缓存，每次从环境变量读取）
# ==========================================
secrets:
  - openai_api_key
  - mail_password
  - database_url

# ==========================================
# 环境变量类型转换
# ==========================================
env_types:
  debug_mode: boolean
  port: integer
  smtp_port: integer
  system_path: path_list
  python_path: path_list
  home_dir: path

# ==========================================
# 路径处理配置
# ==========================================
path_config:
  path_separator: ":"                 # 路径分隔符
  resolve_paths: true                 # 是否解析为绝对路径
  validate_existence: false           # 是否验证路径存在性