log_settings:
  log_level: DEBUG
  detail:
    file: /tmp/app.log
    max_size: 100
anp_sdk:
  debug_mode: true
  host: localhost
  port: 9527
  user_did_path: '{APP_ROOT}/anp_open_sdk/anp_users'
  user_hosted_path: '{APP_ROOT}/anp_open_sdk/anp_users_hosted'
  group_msg_path: '{APP_ROOT}/anp_open_sdk'
  auth_virtual_dir: wba/auth
  msg_virtual_dir: /agent/message
  token_expire_time: 3600
  nonce_expire_minutes: 6
  jwt_algorithm: RS256
  user_did_key_id: key-1
  helper_lang: zh
did_config:
  method: wba
  format_template: did:{method}:{host}%3A{port}:{method}:{user_type}:{user_id}
  router_prefix: /wba
  user_path_template: /{method}/user/{user_id}/did.json
  hostuser_path_template: /{method}/hostuser/{user_id}/did.json
  testuser_path_template: /{method}/test/{user_name}/did.json
  user_types:
    user: user
    hostuser: hostuser
    test: test
  creatable_user_types:
  - user
  hosts:
    localhost: 9527
    user.localhost: 9527
    service.localhost: 9527
    open.localhost: 9527
    127.0.0.1: 9527
  path_templates:
    user_did_path: '{APP_ROOT}/data_user/{host}_{port}/anp_users'
    user_hosted_path: '{APP_ROOT}/data_user/{host}_{port}/anp_users_hosted'
    agents_cfg_path: '{APP_ROOT}/data_user/{host}_{port}/agents_config'
  url_encoding:
    use_percent_encoding: false
    support_legacy_encoding: true
  insecure_patterns:
  - did:wba:localhost:*
  - did:wba:127.0.0.1:*
  - did:wba:*:test:*
  parsing:
    strict_validation: true
    allow_insecure: true
    default_host: localhost
    default_port: 9527
llm:
  api_url: https://api.302ai.cn/v1
  default_model: deepseek/deepseek-chat-v3-0324:free
  max_tokens: 512
  system_prompt: 你是一个智能助手，请根据用户的提问进行专业、简洁的回复。
mail:
  use_local_backend: true
  local_backend_path: '{APP_ROOT}/anp_open_sdk/testuse/mail_local_backend'
  smtp_server: smtp.gmail.com
  smtp_port: 587
  imap_server: imap.gmail.com
  imap_port: 993
env_mapping:
  debug_mode: ANP_DEBUG
  host: ANP_HOST
  port: ANP_PORT
  system_path: PATH
  home_dir: HOME
  user_name: USER
  python_path: PYTHONPATH
  openai_api_key: OPENAI_API_KEY
  mail_password: MAIL_PASSWORD
  database_url: DATABASE_URL
secrets:
- openai_api_key
- mail_password
- database_url
env_types:
  debug_mode: boolean
  port: integer
  smtp_port: integer
  system_path: path_list
  python_path: path_list
  home_dir: path
path_config:
  path_separator: ':'
  resolve_paths: true
  validate_existence: false
