openapi: 3.0.0
info:
  title: DID did:wba:localhost%3A9527:wba:user:3ea884878ea5fbb1 API
  version: 1.0.0
  description: 所有与DID did:wba:localhost%3A9527:wba:user:3ea884878ea5fbb1 关联的服务接口
  x-runtime: nodejs
paths:
  /calculator-js/add:
    post:
      summary: Calculator Agent JS的/calculator-js/add接口
      description: 由 Calculator Agent JS 提供的服务
      tags:
        - Calculator Agent JS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: string
                b:
                  type: string
      responses:
        "200":
          description: 返回结果
          content:
            application/json:
              schema:
                type: object
  /calculator-js/multiply:
    post:
      summary: Calculator Agent JS的/calculator-js/multiply接口
      description: 由 Calculator Agent JS 提供的服务
      tags:
        - Calculator Agent JS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: string
                b:
                  type: string
      responses:
        "200":
          description: 返回结果
          content:
            application/json:
              schema:
                type: object
