info:
  title: Large Language Model AgentAgent API
  version: 1.0.0
openapi: 3.0.0
paths:
  /llm/chat:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                prompt:
                  type: string
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: "\n    APIProcessing function，Now directly use the module's internal\
        \ functions. my_llm_client。\n    It no longer needs to be fromrequestObtain\
        \ from ChinaagentExample。\n    "
