info:
  description: 所有与 DID did:wba:localhost%3A9527:wba:user:5fea49e183c6c211 关联的服务接口
  title: DID did:wba:localhost%3A9527:wba:user:5fea49e183c6c211 API
  version: 1.0.0
openapi: 3.0.0
paths:
  /assistant/assistant/help:
    post:
      description: 由 代码生成助手 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 帮助信息API
      tags:
      - 代码生成助手
  /assistant/calculator/hello:
    post:
      description: 由 代码生成助手 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 代码生成助手的/calculator/hello接口
      tags:
      - 代码生成助手
  /assistant/calculator/info:
    post:
      description: 由 代码生成助手 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 代码生成助手的/calculator/info接口
      tags:
      - 代码生成助手
  /assistant/weather/current:
    post:
      description: 由 代码生成助手 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 获取当前天气API
      tags:
      - 代码生成助手
  /assistant/weather/forecast:
    post:
      description: 由 代码生成助手 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 获取天气预报API
      tags:
      - 代码生成助手
  /calculator/assistant/help:
    post:
      description: 由 我的小本田 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 帮助信息API
      tags:
      - 我的小本田
  /calculator/calculator/hello:
    post:
      description: 由 我的小本田 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 我的小本田的/calculator/hello接口
      tags:
      - 我的小本田
  /calculator/calculator/info:
    post:
      description: 由 我的小本田 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 我的小本田的/calculator/info接口
      tags:
      - 我的小本田
  /calculator/weather/current:
    post:
      description: 由 我的小本田 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 获取当前天气API
      tags:
      - 我的小本田
  /calculator/weather/forecast:
    post:
      description: 由 我的小本田 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 获取天气预报API
      tags:
      - 我的小本田
  /weather/assistant/help:
    post:
      description: 由 代码生成天气 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 帮助信息API
      tags:
      - 代码生成天气
  /weather/calculator/hello:
    post:
      description: 由 代码生成天气 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 代码生成天气的/calculator/hello接口
      tags:
      - 代码生成天气
  /weather/calculator/info:
    post:
      description: 由 代码生成天气 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 代码生成天气的/calculator/info接口
      tags:
      - 代码生成天气
  /weather/weather/current:
    post:
      description: 由 代码生成天气 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 获取当前天气API
      tags:
      - 代码生成天气
  /weather/weather/forecast:
    post:
      description: 由 代码生成天气 提供的服务
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 获取天气预报API
      tags:
      - 代码生成天气
