info:
  title: 代码生成天气Agent API
  version: 1.0.0
openapi: 3.0.0
paths:
  /assistant/help:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 帮助信息API
  /calculator/hello:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 我的小本田的/calculator/hello接口
  /calculator/info:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 我的小本田的/calculator/info接口
  /weather/current:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 获取当前天气API
  /weather/forecast:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: 返回结果
      summary: 获取天气预报API
